databases:
  - name: extreme-fitness-db
    databaseName: extreme_fitness_production
    user: extreme_fitness_user
    plan: free

services:
  - type: web
    name: extreme-fitness-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: extreme-fitness-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
